package com.google.school.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "students")
public class Student {
	@Id // An Autogenerated id (unique for each user in the db)
	//@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "rollNo", nullable = false)
	//, insertable = true, updatable = true)
	private int rollNo;
	@Column(name = "studentName", nullable = false)
	//, insertable = true, updatable = true)
	private String studentName;
	@Column(name = "className", nullable = false)
	//, insertable = true, updatable = true)
	private String className;
//	private Parent parentInfo;
//	private Fee feeInfo;
	
	public Student() {
		super();
	}
	
//	public Student(String studentname, String classname,Parent parentInfo, Fee feeInfo) {
//		this.studentName = studentname;
//		this.className = classname;
//		this.parentInfo = parentInfo;
//		this.feeInfo = feeInfo;
//	}
//
//	public Student(int rollNo, String studentName, String className, Parent parentInfo, Fee feeInfo) {
//		super();
//		this.rollNo = rollNo;
//		this.studentName = studentName;
//		this.className = className;
//		this.parentInfo = parentInfo;
//		this.feeInfo = feeInfo;
//	}
	
	public Student(int rollNo, String studentName, String className) {
		this.rollNo = rollNo;
		this.studentName = studentName;
		this.className = className;
	}
	
	public Student(int rollNo) {
		this.rollNo = rollNo;		
	}
	
	
	// Set and Get Methods.
	public int getRollNo() {
		return rollNo;
	}

	public void setRollNo(int rollNo) {
		this.rollNo = rollNo;
	}
	
	public String getStudentName() {
		return studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}
	public String getClassName() {
		return className;
	}
	public void setClassName(String className) {
		this.className = className;
	}
//	public Parent getParentInfo() {
//		return parentInfo;
//	}
//	public void setParentInfo(Parent parentInfo) {
//		this.parentInfo = parentInfo;
//	}
//	public Fee getFeeInfo() {
//		return feeInfo;
//	}
//	public void setFeeInfo(Fee feeInfo) {
//		this.feeInfo = feeInfo;
//	}
	

}
